# Media types

[mediatypes."application/atom+xml"]
suffixes = ["xml"]

# Hugo

[module.hugoversion]
min = "0.141.0"
extended = true

# Default mounts

[[module.mounts]]
source = "archetypes"
target = "archetypes"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static"
target = "static"

# Bootstrap mounts

[[module.mounts]]
source = "paige/node_modules/bootstrap/dist/css"
target = "assets/css/paige/bootstrap"
includefiles = ["bootstrap.css"]

[[module.mounts]]
source = "paige/node_modules/bootstrap/dist/js"
target = "assets/js/paige/bootstrap"
includefiles = ["bootstrap.bundle.js"]

[[module.mounts]]
source = "paige/node_modules/bootstrap/js/dist"
target = "assets/js/paige/bootstrap"

[[module.mounts]]
source = "paige/node_modules/bootstrap/scss"
target = "assets/css/paige/bootstrap"

# Bootstrap Icons mounts

[[module.mounts]]
source = "paige/node_modules/bootstrap-icons/font/fonts"
target = "static/css/paige/bootstrap-icons/fonts"

[[module.mounts]]
source = "paige/node_modules/bootstrap-icons/font"
target = "assets/css/paige/bootstrap-icons"
includefiles = ["bootstrap-icons.css"]

# FlexSearch mounts

[[module.mounts]]
source = "paige/node_modules/flexsearch/dist"
target = "assets/js/paige/flexsearch"
includefiles = ["flexsearch.bundle.min.js"]

# Katex mounts

[[module.mounts]]
source = "paige/node_modules/katex/dist/contrib"
target = "assets/js/paige/katex"
includefiles = ["auto-render.min.js"]

[[module.mounts]]
source = "paige/node_modules/katex/dist/fonts"
target = "static/css/paige/katex/fonts"

[[module.mounts]]
source = "paige/node_modules/katex/dist"
target = "assets/css/paige/katex"
includefiles = ["katex.min.css"]

[[module.mounts]]
source = "paige/node_modules/katex/dist"
target = "assets/js/paige/katex"
includefiles = ["katex.min.js"]

# Output formats

[outputformats.atom]
basename = "atom"
isplaintext = true
mediatype = "application/atom+xml"
name = "atom"

[outputformats.rss]
basename = "rss"
isplaintext = true
mediatype = "application/rss+xml"
name = "rss"

[outputformats.paige-search]
basename = "paige-search"
isplaintext = true
mediatype = "application/json"
name = "paige-search"
notalternative = true
